### ISSUE TITLE
Unexpected chunk Type: 0x61a5

### ISSUE THREAD

**Issue by snehil-om** [clearthesky/apk-parser#54]
The parser is throwing the following exceptions:
net.dongliu.apk.parser.exception.ParserException: Unexpected chunk Type: 0x61a5
	at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:222)
	at net.dongliu.apk.parser.parser.ResourceTableParser.readPackage(ResourceTableParser.java:93)
	at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:60)
	at net.dongliu.apk.parser.AbstractApkFile.parseResourceTable(AbstractApkFile.java:220)
	at net.dongliu.apk.parser.AbstractApkFile.transBinaryXml(AbstractApkFile.java:157)
	at net.dongliu.apk.parser.AbstractApkFile.parseManifestXml(AbstractApkFile.java:123)
	at net.dongliu.apk.parser.AbstractApkFile.getManifestXml(AbstractApkFile.java:44)

**Comment by hsiafan** [comment]
Can you upload the apk file or provide a link?
